version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: api
  myadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1
    ports:
      - 8080:80
    links:
      - "db:db"
    environment:
      - PMA_ARBITRARY=1
  api:
    depends_on:
      - db
    container_name: api
    build: ./api
    volumes:
      - api_static:/api/static
    ports:
      - "50505:50505"
    links:
      - "db:db"
    environment:
      - MYSQL_DSN=${MYSQL_DSN}
      - SECRET_AUTH=${SECRET_AUTH}
      - ACCESS_EXPIRE_HOUR=${ACCESS_EXPIRE_HOUR}
      - SERVICE_HOST=${SERVICE_HOST}
      - SERVICE_PORT=50505

volumes:
  mysql-data:
  api_static: